


# Hibernate Configuration
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update



spring.application.name=Matcher


spring.datasource.url=jdbc:postgresql://localhost:5432/SmartMatchDatabase
spring.datasource.username=Fynn
spring.datasource.password=changemeinprod!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

logging.level.org.flywaydb=TRACE
logging.level.org.springframework.security=DEBUG

#JWT Stuff
jwt.secret=JGHj3m2FjYV1mzlcBbP5LjsHvgwoHAwdEZk6BKP7GhB
jwt.expiration=300000
